### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by nov1c3** [dnmvisser/nagios-ssllabs-rating#4]
Hello,

Thank you for the script!

I'd appreciate if you could explain how to make it to work with the proxy (Squid)?

export_http/s works fine, but I'd like to pass proxy parameters inside the script.

Thank you.

**Comment by dnmvisser** [comment]
hii, can you give this a try? https://github.com/dnmvisser/nagios-ssllabs-rating/tree/dv_proxy_support

let me know if it works, i will create a release then

thx

**Comment by nov1c3** [comment]
Thank you very much @dnmvisser  -- worked like a charm!

**Comment by dnmvisser** [comment]
Fixed in https://github.com/dnmvisser/nagios-ssllabs-rating/pull/5
